### PR TITLE
Branchjill

### PR DESCRIPTION
**Pull request by Jillderon**

### CODE REVIEW

**Comment by JorisGoosen** [comment]
What did #1037 supposed to refer to?

**Comment by Jillderon** [comment]
@JorisGoosen #1037 referred to an issue in the test release

**Comment by JorisGoosen** [comment]
https://github.com/jasp-stats/jasp-test-release/issues/1037 then?

It works better by posting the entire URL, that way github knows which repository is meant.

**Comment by vandenman** [comment]
@Jillderon  I'm not sure you meant 1037, as you're not assigned to that issue (and it's already closed). Maybe you meant one of [these issues](https://github.com/jasp-stats/jasp-test-release/issues/assigned/Jillderon)?

Also, if you start (or edit) the description of the PR to begin with:

> Fixed \< url to 1st issue fixed by this PR \> 
> Fixed \< url to 2nd issue fixed by this PR \> 
> etc.

then GitHub will automagically close the corresponding issues once this PR is merged :)

**Comment by vandenman** [comment]
the changes in the code look fine btw, but I'd like to know what issue this PR fixes so that I can test if it's actually fixed.

**Comment by Jillderon** [comment]
It was https://github.com/jasp-stats/jasp-test-release/issues/1307. Can the PR be accepted then?

**Review by vandenman — APPROVED** [review]

**Comment by vandenman** [comment]
Looks good to me! @Jillderon for next time, could you not create a branch on jasp-stats/jaspEquivalenceTTests but instead on your own fork [Jillderon/EquivalenceTTests](https://github.com/Jillderon/EquivalenceTTests)?

**Comment by Jillderon** [comment]
@vandenman okay I'll do that! Thanks for reviewing Don :)

**Comment by JorisGoosen** [comment]
That is why I need to make the git-guide ^^

**Comment by vandenman** [comment]
The fault is also on our side, she shouldn't have any rights to push a new branch to this repo.

**Pull request merged**
