### PR TITLE
Unbreak entire module

### PR DESCRIPTION
**Pull request by koenderks**
Closes https://github.com/jasp-stats/INTERNAL-jasp/issues/2240

### CODE REVIEW

**Comment by JohnnyDoorn** [comment]
Any idea why the unit tests are failing? I just tested it and it seemed to have resolved the issue (my plots are not working in my build, but the table is good, so it should be fine?)

**Comment by koenderks** [comment]
I didn’t really look into the functionality itself, maybe @Jillderon can give some advice on if I did something weird or that he unit tests just need to be updated?

**Comment by koenderks** [comment]
Probably best to get this rolling again. @JohnnyDoorn Do you have any idea who can give some info on the unit tests? After that is fixed we can probably get this bug fix this in.

**Comment by JohnnyDoorn** [comment]
@koenderks  are there any papers that use a data example? that could serve as a sanity check maybe?

**Comment by JohnnyDoorn** [comment]
Hmm for me the module works, but yes sorry I completely forgot about this.. is it possible to rerun the unit tests?

**Review by boutinb — APPROVED** [review]

**Comment by EJWagenmakers** [comment]
Yes, most definitely!

**Comment by boutinb** [comment]
@vandenman Can we merge this PR?

**Comment by vandenman** [comment]
@koenderks I'm still seeing this error
image

does that ring a bell?

**Comment by koenderks** [comment]
@vandenman Oef, it has been a long time since I have looked at this. But I do not recognise this

**Comment by koenderks** [comment]
Hmm I do not have the time to dive into this now but since the other stuff works lets merge it

**Pull request merged**
